### ISSUE TITLE
Allow a const argv

### ISSUE THREAD

**Issue by jarro2783** [jarro2783/cxxopts#123]
It is desirable to have a `const` `argv` and `argc` in addition to the mutable one that is already used.

**Comment by MikeGitb** [comment]
could you be more specific? There are three places where a concert could be introduced. Are you talking about being able to pass a `char** const` variable? 

For me the most important thing is that passing a standard argv (`char** argv`) is possible without casting. Long term, being able to pass an `std::vector<std::string_view>` and/ or `std::vector<std::string>` would be nice.

**Comment by jarro2783** [comment]
I'm specifically talking about `parse(int argc, const char** argv)` as per the discussion in #110.

Do you have any other use cases?

**Comment by K-Wone** [comment]
I think it would be nice if the parser manages its own memory rather than modifying the pointers passed in. I mean, why is it allowed to mess up my pointers if it doesn't take care of my memory. 

What if I'm trying to pass the arguments to another function? I have to allocate more space for them. I have to make sure that all of the arguments are deep copied since the cxxopts parser wants a reference to them. I don't know whether the pointers would be changed unless I look deep into the parser. And there is no assurance the arguments won't be modified in future versions of the parser.

**Comment by jarro2783** [comment]
This is fixed in the v3 rewrite now on master.
