### ISSUE TITLE
Potential bug with single character after double dash

### ISSUE THREAD

**Issue by marc2982** [jarro2783/cxxopts#136]
We are using version 2.1.0 and noticed a potential bug.

We have an option defined as:

`("u,url", "The URL to connect to", cxxopts::value<string>()->default_value(url))`

However, if it is called with a typo like so `--u` (instead of `-u`), no exception is thrown, and url is given the default value.

I suspect this is because the u is being treated as a positional argument but have not verified it.

Is this a bug or expected behaviour? I would have expected a space be required after `--` to begin listing the positional arguments.

Also, this change seemed to fix the problem, but as I did not run the tests I'm not sure what all of the repercussions may be.

`   std::basic_regex<char> option_matcher`
`-    ("--([[:alnum:]][-_[:alnum:]]+)(=(.*))?|-([[:alnum:]]+)");`
`+   ("--([[:alnum:]][-_[:alnum:]]*)(=(.*))?|-([[:alnum:]]+)");`

Thanks!

**Comment by jarro2783** [comment]
No the `--` is to treat everything after it as a positional option regardless of hyphens. I think this treats it as a positional option because it doesn't match either a long option or a short option.

That sounds like a bug, it should probably say that you can't have a long option with only one character.

**Comment by jarro2783** [comment]
This has been fixed in b5283241076013b325a8cf881c19829ac1cbbdb5 by treating the `--u` as an error.
