### ISSUE TITLE
Incorrect behavior when passing boolean values in "next argument" style

### ISSUE THREAD

**Issue by zhangpiu** [jarro2783/cxxopts#157]
> Boolean options have a default implicit value of "true", which can be overridden. The effect is that writing -o by itself will set option o to true. However, they can also be written with various strings using either =value or the next argument.

While, passing a boolean value using next argument will not be handled correctly.
e.g.
`--boolean_value=false` is OK, `--boolean_value false` got `boolean_value` being `true`.

**Comment by jarro2783** [comment]
The readme is wrong. It shouldn't say "the next argument". Since it has an implicit value of `true`, there is no way to know whether the next argument is an argument to the boolean or a positional parameter. So I've made it a positional argument, with the only way to set a boolean to false being `=false`.

I'll fix the readme.
