### ISSUE TITLE
The release archives' names don't have "cxxopts" in them

### ISSUE THREAD

**Issue by piotrklos-tcl** [jarro2783/cxxopts#198]
The archives are called for example **v2.2.0.tar.gz**. It should be called **cxxopts-v2.2.0.tar.gz**.

It's a little inconvenient when you download a release because you may not find it in your downloads folder, or it may overwrite another file. You also won't find by name after the download, especially if time passes and you don't remember what the file was called.

**Comment by piotrklos-tcl** [comment]
Also, if I'm collecting libraries in a "deps" or "ext" folder in a project, I have to make an extra folder for the cxxopts zip because otherwise I won't know what it was after a while.

**Comment by jarro2783** [comment]
Good point. I'll fix that. I'll tag a patch version of the current release so there is a correctly named archive.

**Comment by jarro2783** [comment]
I think this is a github limitation, and a lot of projects suffer from the same problem. Github automatically makes a release based on your tag, and the tags in the repository are just version numbers, because it seems redundant to put the repository name in the tag in the repository.
I'll see if I can find a nice way to solve this, although I might just end up tagging them as cxxopts-version.

**Comment by QuLogic** [comment]
Please don't; that'd be redundant.

If you're downloading files as deps for a project, I guess you might have a script for it. GitHub supports adding any trailing name to the URL to produce a tarball of that name, so instead of:
https://github.com/jarro2783/cxxopts/archive/v${version}.tar.gz
you can download it as:
https://github.com/jarro2783/cxxopts/archive/v${version}/cxxopts-${version}.tar.gz

**Comment by jarro2783** [comment]
Thanks, I didn't know that. It also looks like the right filename is set in the content-disposition header. You can get curl to use that with `-J`.

**Comment by jarro2783** [comment]
I just double checked that this URL works: https://github.com/jarro2783/cxxopts/archive/v2.2.0/cxxopts-v2.2.0.tar.gz

I'll close this as it appears to be resolved.
