### ISSUE TITLE
Positional arguments should be required (?)

### ISSUE THREAD

**Issue by 5nizza** [jarro2783/cxxopts#25]
If some positional arguments are not set, then `options.parse(argc, argv)` should print help message and exit.

(just a suggestion -- this is the default behaviour of python argparse)

**Comment by 5nizza** [comment]
in general, this can be customized with the parameter `required`. When it is true, then the parse function should throw exceptions.

**Comment by jarro2783** [comment]
I don't really like the options parser doing too much thinking. My philosophy behind this library is that it is just a basic option parser, and any further logic should be left up to the program.

If the program needs options to be present then I think it is reasonable to leave it up to the program rather than adding extra cases into the options parser. For example, `tar` says the following:

    tar: Cowardly refusing to create an empty archive
    Try `tar --help' or `tar --usage' for more information.

which would be done by the program, after seeing that there are no files specified.

For those reasons I will not be adding any such feature.
