### ISSUE TITLE
Help message for positional arguments

### ISSUE THREAD

**Issue by 5nizza** [jarro2783/cxxopts#26]
help message is somewhat strange for positional arguments:
(taken from your example.cpp)

```
program_name [OPTIONS]

      --positional arg          Positional arguments: these are the arguments
                                        that are entered without an option
```

Is double dash intended?
Should it be smth like?:
```
program_name positional [OPTIONS]

 positional                       Positional arguments: these are the arguments
                                        that are entered without an option
```

thanks!

**Comment by jarro2783** [comment]
This is probably wrong, I will fix it.

**Comment by jarro2783** [comment]
This is a tricky one, because --positional is actually an option. We then parse multiple options as positional using

    options.parse_positional({"input", "output", "positional"});

In this case input and output are actually positional too. What I haven't thought of is if you specify 
`--input` or even worse, `--output`, by themselves, and then have other positional arguments.

**Comment by jarro2783** [comment]
Maybe it would useful to hide an option from the help if it is positional and a container.

There is a bug in the parsing, for the example. If you specify --input or --output, then positional arguments, it should not overwrite the existing settings.
