### ISSUE TITLE
Ship pkg-config file irrelavant to CPack?

### ISSUE THREAD

**Issue by hosiet** [jarro2783/cxxopts#302]
Hi, 

While working on https://tracker.debian.org/pkg/cxxopts , I just realized a previous Merge Request ( #298 ) can help to solve https://bugs.debian.org/975713 .

Shipping an architecture-independent `pkg-config` file (and placing it under `/usr/share/pkgconfig/` instead of `/usr/lib/*/pkgconfig/`) is actually a good idea for a header-only library. I am wondering if the generation of pkgconfig .pc file can be integrated into regular building process, not only limited to packaging and CPack. You may find a simple example at https://www.scivision.dev/cmake-generate-pkg-config/ .

@KOLANICH @jarro2783 I'd like to know your opinions on it. If it looks well, we can make further modification on top of #298 to implement this.

**Comment by KOLANICH** [comment]
Hi.

1. pkg-config is kinda irrelevant to CMake-own discovery mechanism
2. It is also kinda orthogonal to CPack, in the sense all of that are features that can be present or not
3. But it is recommended to use CMake mechanisms for installation, they should generate and install the needed files
4. It is also recommended to use CPack as a source of metadat to keep everything DRY
5. I have a tool https://github.com/prebuilder/prebuilder that heavily automates building of debian packages, but it got broken some times ago and I have no time to fix it. It may make sense to fix it, since it implements among other useful features (like auto-splitting a package into multiple ones, with metadata generation), pulling the metadata from CPack too (I have created a kinda CMake interpreter in python specially for that purpose)

Also, if you are serious about packaging cli parsing libs, I have contributed similar patches to other libs, and also for other unmaintained libs (the unmaintained libs with my patches upon them can be found in https://github.com/HydrArgs ). It'd be very nice if you brought them all into debian repos.

**Comment by hosiet** [comment]
Thanks for the reply. I also prefer mechanisms provided by CMake (i.e. using files under `/usr/lib/cmake/*/*.cmake`), but the architecture-dependent nature of these `.cmake` files made it a headache (https://bugs.debian.org/975713 , builds on 32bit/64bit systems yield different `.cmake` files):

```cmake
# check that the installed version has the same 32/64bit-ness as the one which is currently searching:
if(NOT CMAKE_SIZEOF_VOID_P STREQUAL "8")
  math(EXPR installedBits "8 * 8")
  set(PACKAGE_VERSION "${PACKAGE_VERSION} (${installedBits}bit)")
  set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```

That's why I was proposing shipping architecture-independent pkgconfig file besides regular mechanism. If there are any solution that can directly circumvent the issue above with pure CMake, that would be even better.

For cli parsing libs, I am focusing on those with active upstream and being used by other software, such as current cxxopts. It's basically driven by the needs, and I'm glad to see different software using cli parsing libs to improve user experience.

**Comment by KOLANICH** [comment]
>but the architecture-dependent nature of these .cmake files

Latest versions of CMake support architecture-independent ones.

**Comment by hosiet** [comment]
@KOLANICH Thanks for the hint! I did some searching, and the solution seems to be at https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html#command:write_basic_package_version_file .

I think that well solves the current issue and I will backport related changes in the packaged version.
