### ISSUE TITLE
GNU style incompatibility

### ISSUE THREAD

**Issue by jengelh** [jarro2783/cxxopts#375]
>This is a lightweight C++ option parser library, supporting the standard GNU style syntax for options

Observed in v3.0.0 from the "Putting all together" example of README.md:

```
$ ./a.out --debug
$ ./a.out --debug=1
$ ./a.out --debug=2
terminate called after throwing an instance of 'cxxopts::argument_incorrect_type'
  what():  Argument ‘2’ failed to parse
```

Expected behavior: Fail when --debug has *any* argument, like ls.

```
$ ls --human
1.cpp  a.out
$ ls --human=1
ls: option '--human-readable' doesn't allow an argument
Try 'ls --help' for more information.
```

**Comment by jarro2783** [comment]
The intention with supporting standard syntax is not for programs to have exactly the same behaviour, but for the options to be input in a similar way to the GNU style. In this case since a boolean option is treated as having a value which can be parsed (you can type in true,false,0,1 etc), the value `2` does not parse as a boolean. The exception thrown represents that rather than saying that `--debug` should not take an argument.
