### ISSUE TITLE
default value for double options

### ISSUE THREAD

**Issue by Glavnokoman** [jarro2783/cxxopts#55]
```
options.add_options()
     ("myoption", "myoption description", cxxopts::value<double>()->default_value(0.1));
```

fails with:
`/home/xs/proj/daedalean/exp/user/xs/vo_eval/src/cpp/main.cpp:25: error: reference to type 'const std::string' (aka 'const basic_string<char>') could not bind to an rvalue of type 'double'
                           , cxxopts::value<double>()->default_value(0.1));`

it looks like default values are only supported for strings at the moment. Might be a good idea to fix the documentation before the code fix is ready.

**Comment by jarro2783** [comment]
I'll take a look at this.

**Comment by jarro2783** [comment]
This is going to be a tricky one. The `default_value` function is a virtual function, so it can't be templated. I'll have to work out how to refactor this so that the original base class can be accessed when adding options.

**Comment by jarro2783** [comment]
Sorry it's taken me so long to look at this. I just realised that this is intended, and everything works fine if you pass strings to `default_value`.

When dealing with default and implicit values, the parser actually parses the string that you provide using the parser for the type that you have specified rather than taking an object of the correct type for the default. So in other words, you can write `default_value("0.1")`.

Is this good enough for you, or do you have a use case where you need to pass an actual value of the required type?

**Comment by Glavnokoman** [comment]
That is perfectly fine for me. It is just a bit non-intuitive, so a bit of documentation would be nice. Thanks a lot for your work.

**Comment by jarro2783** [comment]
Sure, I'll improve the documentation.
