### ISSUE TITLE
Using std::vector<std::string> instead of argc, argv

### ISSUE THREAD

**Issue by gouarin** [jarro2783/cxxopts#66]
Before you reply to my issue https://github.com/jarro2783/cxxopts/issues/65, I have a question.

In our program, we need to parse a std::string instead of using argc, argv. The options are in this string. So to be able to use cxxopts I do a hack of the Options class and add two functions

```
void parse(std::vector<std::string>& argv);
void checked_parse_arg 
        (
        std::vector<std::string>& argv,
        int& current,
        std::shared_ptr<cxxopts::OptionDetails> value,
        const std::string& name
        );
```

The use case is

```
std::istringstream iss(line);
std::vector<std::string> results((std::istream_iterator<std::string>(iss)),
                                                  std::istream_iterator<std::string>());
auto options = get_options();
options.parse(results);
```

where `line` is the string to parse and we split this line with the space delimiter and set the result in a vector of string.

Did you already think about this use case ? What is the best thing to do ? Add a PR with this work ?

**Comment by jarro2783** [comment]
I had to use a hack in the tests to pass in an array of character pointers for argv. Giving it a vector of strings would obviously be much simpler.

This seems pretty reasonable to do. What if you define `parse(const std::vector<std::string>&)` so that it constructs an array of pointers to the `string.c_str()` values and pass that to the actual `parse`?

Do you ever care about any unswallowed arguments though? You could deal with that by modifying the input `vector` or returning a new one.

**Comment by gouarin** [comment]
@jarro2783 I have fixed my implementation with the current version of cxxopts. So you can do the release.

@SylvainCorlay, I let you do the conda package when the release will be done.
