### ISSUE TITLE
Positional parameters cannot follow a no-parameter option

### ISSUE THREAD

**Issue by Malvineous** [jarro2783/cxxopts#84]
If you have the following scenario:

* Option `-c` that takes no parameters
* Positional parameters

The the following command line works:

    ./example blah -c

However this command line fails:

    ./example -c blah
    Argument ‘blah’ failed to parse

Since the `-c` option takes no parameters, it would be nice if it could be used anywhere in the command line and not just at the end.

In case it's relevant, if you have another option that takes a parameter then that does work:

    ./example -c -t test blah

So if a no-parameter option is followed by another dashed option then it works, but when it's followed by a potential positional parameter then it fails.

**Comment by jarro2783** [comment]
Just so you know what's going on: this was caused by 6c9bae4a071d6892069e6bd998fbae47193df0a8, which added parsing for boolean values, so that you can write things like --foo=false to explicitly disable an option. The problem is that it treated booleans as taking a parameter now, so `-c blah` tries to parse `blah` as a boolean value.

It works in a lot of use cases because you might write something like `-c -f file`, and the `-f` looks like an option, so it skips it.

The short story is that the handling of implicit values is a bit broken, and the entire parser loop is a bit of a mess. So I'll have to work out the best way to patch or rewrite this so that it behaves in a sane way.

**Comment by Malvineous** [comment]
No worries at all, thanks for the update!

Sounds like it could be tricky if you consider `-c true` as equivalent to `-c`.  I guess if only the long variant is allowed and only with an equals sign (`--foo=false`) then you could get away with it, but as soon as you allow a space I think you'll end up with ambiguity.  Take this for example:
```
(1) $ ./power-on true true          # Turn on devices 1 and 2
(2) $ ./power-on --delay=true true  # Turn on only device 1 with a delay
(3) $ ./power-on --delay true true  # Turn on devices 1 and 2 with a delay (or maybe only device 1 with a delay?)
```
I think (3) is always going to be ambiguous unless you require the equals as in (2).

**Comment by jarro2783** [comment]
Yes I think that's how I'll fix it. It's too ambiguous otherwise, especially when `--delay --foo` is parsed as two arguments because of the `-` at the start of `--foo`.
