### ISSUE TITLE
read options from standard input

### ISSUE THREAD

**Issue by campisano** [jarro2783/cxxopts#90]
Does make sense to have read options from stdin?

Something like
`cat args1.txt | cxxopts_binary`

I have a set of files defining different argument set, actually I can do the opposite
```
cxxopts_binary `cat args1.txt`
```

but may be new small feature: the parse method, that actually require `int argn` and `char ** argv`, could be overridden to get a std::string too.

**Comment by jarro2783** [comment]
In order to keep cxxopts as simple as I can, I don't think this is the sort of functionality that I would really like to add. There are a couple of issues with doing this:

1. A parser would be non trivial because things like quotes and spaces matter.
2. The current library modifies `argv` and `argc`, effectively swallowing recognised arguments and leaving those that are unrecognised, meaning that it isn't clear what to do with a string.
3. `stdin` might be used for something else and it might be desirable to read from a file too, so a much more general configuration parser would be more useful anyway.

The functionality could be implemented by parsing the file yourself, turning that into an array of `char*` and passing it to `cxxopts`.

I don't really want to go down the road of point 3, because cxxopts was never meant to be a general configuration parser. There are plenty of other great libraries for doing that if you want it.

**Comment by campisano** [comment]
I see, and agree, the scope is other.

Thanks,
Riccardo
