### ISSUE TITLE
options.count() is never 0

### ISSUE THREAD

**Issue by WarShoe** [jarro2783/cxxopts#96]
Even if I don't pass any options (my command line is empty), options.count("any-option") returns 1. So basically the test example does not work as expected. Also, in the test file you never check for zero options count values: `CHECK(result.count("some-option") == 0);`

**Comment by jarro2783** [comment]
Is that because they are boolean options?

I recently merged a pull request that added a default value of false for all boolean options. That does have the side effect that count is always >= 1. That is possibly not desirable because it breaks anyone trying to do `if (result.count("option") > 0)`.

The reason for the pull request was so that you could unconditionally do `if (result.get<bool>("option"))`. It would probably be better if both worked, and that `count` returns the number of times an option was actually given, excluding default values.

**Comment by WarShoe** [comment]
Indeed, the last pull-requested code is responsible. Reverting it fixes the issue. 

I recommend to add a test for result.count("myoption")==0 in case "myoption" was not passed in the command line.
